/**
 * Created by Administrator on 2017/3/3.
 */
(function(angular){
    var router = angular.module('routeApp',['ctrlApp',"ngRoute"]);
    router.config(['$routeProvider','$locationProvider',function($routeProvider,$locationProvider){

        $routeProvider
            .when('/',{
                templateUrl:'modules/template/index.html',
                controller:"indexCtrl"
            }).when('/myform',{
                templateUrl:'modules/template/myform.html',
                controller:"myFormCtrl"
            }).when('/news',{//消息列表
                templateUrl:'modules/template/news.html',
                controller:"newsCtrl"
            }).when('/jifen',{//积分列表
                templateUrl:'modules/template/jifen.html',
                controller:"jifenCtrl"
            }).when('/kdchaxun',{//快递查询
                templateUrl:'modules/template/kuaidichaxun.html',
                controller:"kdchaxunCtrl"
            }).when('/eText/:type',{//关于我们
                templateUrl:'modules/template/aboutUs.html',
                controller:"singlesCtrl2"
            }).when('/fankui/:type',{//反馈
                templateUrl:'modules/template/fankui.html',
                controller:"singlesCtrl"
            }).when('/tousu/:type',{//投诉
                templateUrl:'modules/template/tousu.html',
                controller:"singlesCtrl"
            }).when('/formMsg/:type/:orderId',{//订单详情
                templateUrl:'modules/template/formMsg.html',
                controller:"formMsgCtrl"
            }).when('/waitGetMsg/:type',{
                templateUrl:'modules/template/daiqianshouMsg.html',
                controller:"msgCtr"
            }).when('/finishMsg/:type',{
                templateUrl:'modules/template/finishMsg.html',
                controller:"msgCtr"
            }).when('/sendAddress/:type',{//寄收货地址
                templateUrl:'modules/template/sendAddress.html',
                controller:"getAddressCtrl"
            }).when('/downForm',{//快递下单
                templateUrl:'modules/template/downForm.html',
                controller:"downFormCtrl"
            }).when('/pay/:type/:price',{//支付
            	templateUrl:'modules/template/pay.html',
                controller:"payCtrl"
            }).when('/selectAddress',{//选择当前所在城市
            	templateUrl:'modules/template/citySelect.html',
                controller:"selectAddressCtrl"
            }).when('/selfCenter',{//修改个人资料
            	templateUrl:'modules/template/selfCenter.html',
                controller:"indexCtrl"
            }).when('/jifenmall',{//积分商城
            	templateUrl:'modules/template/jifenmall.html',
                controller:"jifenmallCtrl"
            }).when('/productMsg/:type',{//商品详情
            	templateUrl:'modules/template/productMsg.html',
                controller:"productMsgCtrl"
            }).when('/sureForm/:type',{//商品详情
            	templateUrl:'modules/template/sureForm.html',
                controller:"sureFormCtrl"
            }).when('/ticket',{//优惠券
            	templateUrl:'modules/template/ticket.html',
                controller:"ticketCtrl"
            }).when('/layout',{//退出
            	templateUrl:'modules/template/ticket.html',
                controller:"layoutCtrl"
            }).when('/paySuccess',{//退出
            	templateUrl:'modules/template/paySuccess.html',
                controller:"paySuccessCtrl"
            }).when('/kuaidiList',{//退出
            	templateUrl:'modules/template/kuaidiList.html',
                controller:"kdchaxunCtrl"
            }).when('/sheZhi',{//设置
            	templateUrl:'modules/template/sheZhi.html',
                controller:"sheZhiCtrl"
            }).otherwise('/');
            $locationProvider.hashPrefix("");
    }])
})(angular);